# Generated by Django 4.2.1 on 2023-05-29 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Focable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('tipo', models.CharField(blank=True, max_length=20, null=True)),
                ('subtipo', models.CharField(blank=True, max_length=20, null=True)),
                ('capacidad', models.SmallIntegerField(blank=True, null=True)),
                ('buffer', models.SmallIntegerField(blank=True, null=True)),
                ('marca', models.CharField(blank=True, max_length=20, null=True)),
                ('geometria', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'focable',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Foconexion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=10, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(blank=True, max_length=20, null=True)),
                ('subtipo', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'foconexion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Foenlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=10, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(blank=True, max_length=20, null=True)),
                ('subtipo', models.CharField(blank=True, max_length=20, null=True)),
                ('capacidad', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'foenlace',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Foodf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('geometria', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'foodf',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Fohilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hilo', models.SmallIntegerField(blank=True, null=True)),
                ('posicion', models.SmallIntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=10, null=True)),
                ('buffer', models.SmallIntegerField(blank=True, null=True)),
                ('colorbuffer', models.CharField(blank=True, max_length=10, null=True)),
                ('ststecnico', models.CharField(blank=True, max_length=10, null=True)),
                ('stsocupacion', models.CharField(blank=True, max_length=10, null=True)),
                ('stsoperativo', models.CharField(blank=True, max_length=10, null=True)),
                ('cable', models.ForeignKey(blank=True, db_column='cable', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='troncal.focable')),
            ],
            options={
                'db_table': 'fohilo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Foenlacedet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.SmallIntegerField(blank=True, null=True)),
                ('fila', models.SmallIntegerField(blank=True, null=True)),
                ('columna', models.SmallIntegerField(blank=True, null=True)),
                ('idenlace', models.ForeignKey(blank=True, db_column='idenlace', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='troncal.foenlace')),
                ('idhilo', models.ForeignKey(blank=True, db_column='idhilo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='troncal.fohilo')),
            ],
            options={
                'db_table': 'foenlacedet',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Fodio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SmallIntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('sala', models.SmallIntegerField(blank=True, null=True)),
                ('rack', models.SmallIntegerField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=20, null=True)),
                ('subtipo', models.CharField(blank=True, max_length=20, null=True)),
                ('tabla', models.CharField(blank=True, max_length=30, null=True)),
                ('externo', models.IntegerField(blank=True, null=True)),
                ('odf', models.ForeignKey(blank=True, db_column='odf', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='troncal.foodf')),
            ],
            options={
                'db_table': 'fodio',
                'managed': True,
            },
        ),
    ]
